### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by axplix** [harbassan/spicetify-stats#10]
![image](https://github.com/harbassan/spicetify-stats/assets/134534381/cbf87ccf-d644-4311-9284-cb6178381c5f)
we dont see the statistics icon and the display is bugged any solution? i tried reinstall it, and it didnt work

**Comment by harbassan** [comment]
will look into it later

**Comment by harbassan** [comment]
doesn't seem like this has anything to with the custom app, its most likely caused by something else. Make sure spicetify is fully up to date and everything.
