### ISSUE TITLE
Library Analysis crashes when choosing 'My Playlists'

### ISSUE THREAD

**Issue by itsmohmans** [harbassan/spicetify-stats#11]
![image](https://github.com/harbassan/spicetify-stats/assets/55551984/f3c24e82-018c-43a3-993c-215a7e8e27ad)

When I go to Library tab, it analyzes my library, and it works, but when I choose 'My Playlists' from this dropdown menu
![image](https://github.com/harbassan/spicetify-stats/assets/55551984/ff896c1e-3fa0-47b1-9578-66d7bdfbf291)
 it crashes every time and reloading doesn't help.
 
OS: Manjaro Linux
Spotify: 1.2.9.743.g85d9593d stable by Flatpak
Spicetify: 2.18.1
Theme: Nord
Custom apps: Marketplace and Stats

**Comment by raem-haq** [comment]
Mine crashes when you click "Library" I don't see "My Playlist"

**Comment by harbassan** [comment]
could you try installing the latest version and see if that changes anything

**Comment by itsmohmans** [comment]
Now after I updated it, it stopped working at all and crashes the whole app. I have no clue how to debug it since DevTools are not available in the Spotify app, but I'll try it again later on a fresh spotify+spicetify installs

**Comment by harbassan** [comment]
could you show the devtools logs

**Comment by itsmohmans** [comment]
Here it is
![image](https://github.com/harbassan/spicetify-stats/assets/55551984/3f6e2591-6dfe-4921-87e9-4451be872395)

**Comment by harbassan** [comment]
i just made a fix, reinstall the app using the dist branch and it should be working.

**Comment by itsmohmans** [comment]
Great! it now works perfectly, thank you!
