### ISSUE TITLE
Something went wrong, try reloading the page

### ISSUE THREAD

**Issue by SenrirenTokyo** [harbassan/spicetify-stats#12]
Everytime I click on statistics it crashes spotify with that message.
![image](https://github.com/harbassan/spicetify-stats/assets/98506880/d8c1116f-77c4-4356-a38c-bd8e5dfab036)

**Comment by SkyPlaza1** [comment]
same here

**Comment by wysteria444** [comment]
I had the same issue. When you download the zipped file open the folder and take the file folder that is in the folder, rename and move that folder into custom apps in the spicetify folder.

**Comment by SkyPlaza1** [comment]
i did exactly that

**Comment by harbassan** [comment]
send a a screenshot of your custom apps folder, the stats folder within it, and your config file

**Comment by SkyPlaza1** [comment]
![configfile](https://github.com/harbassan/spicetify-stats/assets/134329462/d9780263-b6f5-4e1e-9ca3-e21de916126f)
![customappsfolder](https://github.com/harbassan/spicetify-stats/assets/134329462/267626ae-c633-4974-9528-7e43fa8cfad4)
![statsfolder](https://github.com/harbassan/spicetify-stats/assets/134329462/023c2eee-55e9-494b-adbc-7b1f1ddbdaad)

**Comment by harbassan** [comment]
Ok that's fine, could you send a ss of the console error you get as soon as you click on the stats app?

**Comment by SkyPlaza1** [comment]
it started working now for some reason. i didn't do nothing, just opened, tho "library" tab seems to be stuck at "analysing your library" screen. 
![analysingyourlibrary](https://github.com/harbassan/spicetify-stats/assets/134329462/49092e54-9fac-4c14-bb39-ca56354a957c)

**Comment by harbassan** [comment]
try installing the latest version and see if that fixes anything.

**Comment by marizzz95** [comment]
the issue is there is no index file

**Comment by harbassan** [comment]
there is an index file, just make sure its in the right place and that spicetify is up to date

**Comment by SenrirenTokyo** [comment]
Just wanted to say it all works fine after doing spicetify -upgrade! thx much m8

**Comment by SenrirenTokyo** [comment]
to explain further for anyone having issues:
upgrade Spicetify with spicetify -upgrade, make sure you are on spicetify 2.20.0  and literally just follow the instructions and it *should* work, make sure u do the normal stuff u do getting spicetify to work
