### ISSUE TITLE
No index.js file?

### ISSUE THREAD

**Issue by raem-haq** [harbassan/spicetify-stats#13]
Hey,
I'm trying to install but I get the error Custom app "stats" does not have index.js error. I'm pretty new to github but I've tried looking for an index.js in Code. Please, could you tell me where it is (or how to fix the problem).
Thank you for your work.

**Comment by InetSyndr** [comment]
https://github.com/harbassan/spicetify-stats/archive/refs/heads/dist.zip

**Comment by wysteria444** [comment]
I had the same issue. When you download the zipped file open the folder and take the file folder that is in the folder, rename and move that folder into custom apps in the spicetify folder.

**Comment by harbassan** [comment]
@raem-haq fixed?

**Comment by raem-haq** [comment]
Oh sorry, I forgot. Yes InetSyndr's post fixed it.
