### ISSUE TITLE
Top Artists Broken

### ISSUE THREAD

**Issue by shadowyy0** [harbassan/spicetify-stats#14]
Every top artist category besides past 4 weeks causes the page to go unresponsive and it asks you reload it.

**Comment by harbassan** [comment]
could you show the console errors by using devtools.

**Comment by shadowyy0** [comment]
![image](https://github.com/harbassan/spicetify-stats/assets/134759996/b4d44bad-84c7-4810-a737-28738553ebf4)
Here are the console errors in the devtools section

**Comment by harbassan** [comment]
I've figured out the issue, will fix soon.

**Comment by harbassan** [comment]
@shadowyy0 this should be fixed now, install the latest release.
