### ISSUE TITLE
can't install this

### ISSUE THREAD

**Issue by n1cklim** [harbassan/spicetify-stats#15]
I can't install this extension. On Sidebar section yes, it appears, but it throws error.
![proof](https://github.com/harbassan/spicetify-stats/assets/122570849/3c68e868-29fe-432b-8760-6e8779ebe24b)

On the seccond image says that something went wrong, try reloading (in spanish)
![`proof2](https://github.com/harbassan/spicetify-stats/assets/122570849/eaa6679c-d22d-4313-acbb-0ac5e7737d5a)

**Comment by harbassan** [comment]
make sure files are in the right place and spicetify is up to date

**Comment by n1cklim** [comment]
I'll have a look. Thanks.
