### ISSUE TITLE
there is no index.js

### ISSUE THREAD

**Issue by alazdacoder** [harbassan/spicetify-stats#16]

**Comment by MasterLandX** [comment]
I have the same problem

**Comment by harbassan** [comment]
make sure the files are in the right place and in a folder called 'stats', make sure spicetify is up to date.

**Comment by CrispyMB** [comment]
> make sure the files are in the right place and in a folder called 'stats', make sure spicetify is up to date.

i got spicetify today and i did everything it says but it looks like this now
![image](https://github.com/harbassan/spicetify-stats/assets/136269696/44732692-9f08-4730-a452-77a722c31277)

**Comment by harbassan** [comment]
could I see your config.xpui file, it seems like you might've entered stats twice.

**Comment by CrispyMB** [comment]
I understand how it looks like i made 2 but i just tried twice and the same thing happened. But i think you should make some kind of uninstallment code. I fixed mine cuz i got hyperfocus and accidentally sat awake to 1am (sweden) with absolutely 0 coding experience.
