### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Diveball** [harbassan/spicetify-stats#18]
Whenever I click stats it makes me reload the app.

**Comment by harbassan** [comment]
could you show the devtools console logs?

**Comment by Mona-Lott** [comment]
Same issue.
![Screenshot 2023-06-11 205801](https://github.com/harbassan/spicetify-stats/assets/98423197/771cc828-f2eb-4dd0-a4cf-837d7850f857)

**Comment by Mona-Lott** [comment]
Just installed both the app and spiceify freshly

**Comment by harbassan** [comment]
when you show the devtools, could you show it just as the error occurs.

**Comment by Mona-Lott** [comment]
![image](https://github.com/harbassan/spicetify-stats/assets/98423197/ffcff0a3-d8af-4904-a494-98774650302d)

**Comment by harbassan** [comment]
So apparently this issue has nothing to do with the code itself but is just some weird file/loading behavior. You could just try re-applying spicetify using `spicetify apply` and see if that fixes it. Otherwise i'm not sure
