### ISSUE TITLE
No index.js

### ISSUE THREAD

**Issue by Dooty1358** [harbassan/spicetify-stats#19]
When applying the custom apps spicetify says 
:error Custom app "stats" does not have index.js
![Screenshot 2023-06-17 150655](https://github.com/harbassan/spicetify-stats/assets/136927869/8824b25f-6885-44e8-8e04-7a9125a0222a)

**Comment by LoganWolfie** [comment]
you need to take the file inside the one you extracted and use that one. 
This is the one you need to rename.
![image](https://github.com/harbassan/spicetify-stats/assets/72407034/3a0cc0cc-d07a-453a-b92b-ee8f422845ea)

**Comment by LoganWolfie** [comment]
![image](https://github.com/harbassan/spicetify-stats/assets/72407034/2f7b2769-0463-46e5-bb7e-933b39f73473)
the 2nd one.

**Comment by german-ux** [comment]
hi, im having the same issue but i made sure stats is in the custom apps folder.

<img width="1317" alt="Screenshot 2023-06-19 at 3 49 24 PM" src="https://github.com/harbassan/spicetify-stats/assets/66699192/b5326781-9fb0-480b-8c36-7c19bc94438b">

<img width="530" alt="Screenshot 2023-06-19 at 3 50 22 PM" src="https://github.com/harbassan/spicetify-stats/assets/66699192/45420bc8-180e-4847-861d-63d8f1533a4e">

**Comment by Olivernio** [comment]
Hello, I had the same error, until I downloaded the folder from the blue link, in the "Manual Installation" section, inside that downloaded folder is the 'index.js' file.

[Reference image]
![chrome_U64HaoADDu](https://github.com/harbassan/spicetify-stats/assets/57511524/4221a14b-0c4f-4ee7-8db1-5b85b50ee6bd)

**Comment by Dooty1358** [comment]
Thank you

**Comment by Dooty1358** [comment]
Thank you

**Comment by german-ux** [comment]
i have the same index.j in my stats folder but my spotify still shows up as this 

![](https://user-images.githubusercontent.com/66699192/246948992-b5326781-9fb0-480b-8c36-7c19bc94438b.png)

could it be that im on a Mac?

**Comment by harbassan** [comment]
it should be fine on mac, could you open up that stats folder that you have in your custom apps folder. It should be called 'stats' exactly and have directly inside it the files 'index.js', 'manifest.json' etc.
