### ISSUE TITLE
"Analysing your library" stucked

### ISSUE THREAD

**Issue by WalterBiely** [harbassan/spicetify-stats#21]
When I select Library. it says "Analysing your library" and nothing happens.

**Comment by subflame** [comment]
same here
latest spotify, latest spicetify
i listen for 5 hours today and stats add only 25 tracks but zero in artist genres and library

**Comment by harbassan** [comment]
@WalterBiely could i see the console logs just as you open the library tab.

**Comment by harbassan** [comment]
> i listen for 5 hours today and stats add only 25 tracks but zero in artist genres and library

It is 'top-genres' and it is fetched according to spotify, so if it is inaccurate in any way then there's nothing I can do about that unfortunately. As for the library, it only tracks songs in your playlists. So if you didnt add a song yo any of your saved playlists it will not update.

**Comment by zeinou705** [comment]
![Capture d’écran 2023-06-24 220338](https://github.com/harbassan/spicetify-stats/assets/137653957/6a223178-a02b-4e3e-81fc-03b82fb96438)

![Capture d’écran 2023-06-24 220444](https://github.com/harbassan/spicetify-stats/assets/137653957/0684b27f-d311-4dd7-8b7d-d7ac6c32990c)

**Comment by Ishanlnx** [comment]
![image_2023-06-25_153920613](https://github.com/harbassan/spicetify-stats/assets/125047210/613b295f-d0fc-446c-aca3-84f82580bedd)
![image_2023-06-25_153809630](https://github.com/harbassan/spicetify-stats/assets/125047210/73351179-a9d5-4dbb-af89-de05a479b243)

**Comment by zeinou705** [comment]
we have the same problem

**Comment by harbassan** [comment]
make sure your files are in the right place and have the right name. There should be a folder in your custom apps folder called 'stats' which directly contains the files.

**Comment by jeroentvb** [comment]
> @WalterBiely could i see the console logs just as you open the library tab.

It's only logging a whole lot of these lines. But that's also happening on the other pages of the stats app.
![image](https://github.com/harbassan/spicetify-stats/assets/36192730/2ef99f0b-e07a-41d7-a6fd-bfac7923f171)

**Comment by harbassan** [comment]
yeah it doesnt seem like there are any errors showing, could you scroll all the way through and look for a red higlighted log.

**Comment by jeroentvb** [comment]
The console doesn't show any errors related to spicetify-stats, and while I was checking for errors the library page loaded. So I guess it just loads *really* slow.

**Comment by DrInbred** [comment]
Is the "Analysing Your Library" problem fixed. I installed spicetify through powershell and I followed the instructions of installation of this repository. Everything works except the "Analysing Your Library" feature. It's just stuck.

**Comment by jeroentvb** [comment]
> How do you see the console logs?

Enter `spicetify enable-devtools` in your console of choice, right click the bottom of the spotify window and select `inspect element`, then click on console in the top bar of the window that opened.

**Comment by MirasNurtazin** [comment]
Hello guys!

> make sure your files are in the right place and have the right name. There should be a folder in your custom apps folder called 'stats' which directly contains the files.

Hello! I have the exact same problem and I checked all of that several times. Everything seems right. So how do I solve this issue? Or at least delete that "Stats" icon? I'm new to all these things so I don't really understand most of the things going on there.

**Comment by harbassan** [comment]
For anyone having this issue, please could you screenshot the console logs, specifically the error messages relating to 'stats' otherwise I have no way of fixing the issue. There's no point in just saying you have the issue, I need to see the logs.

**Comment by cretaceous-rexd** [comment]
> For anyone having this issue, please could you screenshot the console logs, specifically the error messages relating to 'stats' otherwise I have no way of fixing the issue. There's no point in just saying you have the issue, I need to see the logs.

After switching to Library tab:

![image](https://github.com/harbassan/spicetify-stats/assets/62309753/cc9ba70c-30f0-4f81-ac03-4066d787514c)

**Comment by harbassan** [comment]
ok so it seems like a certain song is causing an issue. could you copy the whole link the error is showing (api.spotify one) and paste it. the full link would be quite long.

**Comment by cretaceous-rexd** [comment]
`https://api.spotify.com/v1/artists?ids=` seems to be the full link
however there is `sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=01` as well when I tried again, not an api.spotify link tho
[xpui.app.spotify.com-1691237307653.log](https://github.com/harbassan/spicetify-stats/files/12267040/xpui.app.spotify.com-1691237307653.log)

**Comment by harbassan** [comment]
the full link would be a lot longer, i forgot exactly how to get it but you should definitely be able to find it. Also, do you have a lot of local tracks by any chance

**Comment by cretaceous-rexd** [comment]
I have 165 local tracks (according to Spotify)
As for the spotify link, I couldn't find the full link after searching 'stats'/'spotify'/other words in the Network tab, and the Console tab only says the shortened link.

**Comment by cretaceous-rexd** [comment]
There was a one before involving a 'rootlist' link, couldn't replicate it
![image](https://github.com/harbassan/spicetify-stats/assets/62309753/d57f7ac8-6a23-47e9-a9ee-424a9f8e12c2)

**Comment by harbassan** [comment]
ok i'm pretty certain this has to do with local artists messing with the api request, ill try and fix this soon.
