### ISSUE TITLE
hi! sorry first time using this! error message when clicking on button. 90% sure it is user error! would like help!

### ISSUE THREAD

**Issue by domojobu** [harbassan/spicetify-stats#22]
![Screenshot 2023-07-06 020546](https://github.com/harbassan/spicetify-stats/assets/138769241/de3b9537-17e1-46e4-8a35-5d6132f21638)

**Comment by domojobu** [comment]
i used the powershell method and have the current version

**Comment by domojobu** [comment]
i dont have a spicetify folder T-T

**Comment by harbassan** [comment]
read the spicetify guide to find your spicetify/customapps folder: https://spicetify.app/docs/advanced-usage/custom-apps. Make sure you download and put the stats folder into there, then add it to your config as shown in the guide. after that you should be all good.
