### ISSUE TITLE
custom app "stats" not found

### ISSUE THREAD

**Issue by breashea** [harbassan/spicetify-stats#24]
Hi, when I run the commands in the powershell, it says "custom app "stats" not found" even though I followed the instructions renaming the folder "stats" and putting it in the custom apps folder. When I pull up Spotify, there's a stats tab but that simple displays an error message of "something went wrong, please try reloading the page". Any help would be appreciated, thank you!

**Comment by deedree** [comment]
Change the name of the folder from 'spicetify-stats-dist' to 'stats' that will fix it.

**Comment by breashea** [comment]
As stated in my original post, I already did that and it's still saying it
can't be found, which is the issue.

Thanks!

**Comment by christmias** [comment]
im having the same issue as well

**Comment by harbassan** [comment]
could you screenshot the custom-apps folder and also the stats folder just to make sure thats not the issue.

**Comment by breashea** [comment]
See screenshots below for the issue as it's appearing for me. Thanks

![customapps](https://github.com/harbassan/spicetify-stats/assets/140680348/1f2a53bd-f2dd-4b45-b372-9f4ddae08450)
![stats](https://github.com/harbassan/spicetify-stats/assets/140680348/2c8fc959-5f6a-4832-a3ff-e476bef905f9)
![error](https://github.com/harbassan/spicetify-stats/assets/140680348/4a1e7c79-7641-433c-a303-04cf45d34caa)

**Comment by harbassan** [comment]
Ok, so unless you havent updated spicetify in a very long time, im pretty sure you're in the old folder right now. The actual folder would be in `C:\Users\user\AppData\Roaming\spicetify` or whatever it shows when you run the command `spicetify path -a root`.

**Comment by xXAGENT87Xx** [comment]
im having the same issue! how do i un-apply the new config

**Comment by bacalaor** [comment]
> Ok, so unless you havent updated spicetify in a very long time, im pretty sure you're in the old folder right now. The actual folder would be in `C:\Users\user\AppData\Roaming\spicetify` or whatever it shows when you run the command `spicetify path -a root`.

iv'e updated it and it's the same problem

**Comment by harbassan** [comment]
The only thing I can say is make sure that the folder layout is correct, that is definitely the problem here. It should be the correct spicetify folder (the one I mentioned) and structured exactly how i say in the readme.

**Comment by shurgbee** [comment]
I also had a same issue and manually installing the .zip file from [releases ](https://github.com/harbassan/spicetify-apps/releases/tag/stats-v1.1.1)and adding the contents into the stats folder worked for me. It could be an issue with the installer.
