### ISSUE TITLE
Icon Error

### ISSUE THREAD

**Issue by Hrushal-Nikhare** [harbassan/spicetify-stats#30]
ON bloom theme the stats icon appears is the same as Home
![image](https://github.com/harbassan/spicetify-stats/assets/82302201/490712b7-de2b-4fe2-8688-529827b7c0aa)

**Comment by Hrushal-Nikhare** [comment]
tried with other themes looks like a problem with bloom

**Comment by harbassan** [comment]
youre gonna have to open the issue on the bloom theme's repo, since this is an issue with their custom icons.
