### ISSUE TITLE
[bug] Artists Profile Pictures appear blurry

### ISSUE THREAD

**Issue by Legeend28** [harbassan/spicetify-stats#31]
![Screenshot 2023-09-14 231233](https://github.com/harbassan/spicetify-stats/assets/91764792/81d5b55d-9c25-441e-a40c-d0998de1bea5)

some artists profile pictures appear blurry. this isnt a major bug or anything but it is a bit weird.

**Comment by harbassan** [comment]
The reason for this is just because Spotify doesn't store a high quality version of their artist profile picture. Nothing I can really do about this unfortunately, luckily it doesn't happen to that many.
