### ISSUE TITLE
[bug] Crashes when trying to open.

### ISSUE THREAD

**Issue by Lrive** [harbassan/spicetify-stats#32]
![image](https://github.com/harbassan/spicetify-stats/assets/57817962/48ce8f5e-3e6a-437c-a4be-211a97f718f2)
After clicking on the Statistics button, the app has to reload, and nothing else works after that.

**Comment by Lrive** [comment]
![image](https://github.com/harbassan/spicetify-stats/assets/57817962/3c3e8101-2b7d-4bdf-8664-f550e4840a52)
maybe this can help?

**Comment by zephyrus0001** [comment]
its happening to me and when i download it says stats is missing index.js
