### ISSUE TITLE
Clicked library and now Stats refuses to load

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [harbassan/spicetify-stats#39]
![image](https://github.com/harbassan/spicetify-stats/assets/138950887/3a1586c4-5f64-4ff7-8ed3-d57445b51294)

**Comment by ADaga460** [comment]
https://github.com/harbassan/spicetify-stats/issues/40

read this thread

**Comment by cuicuidu** [comment]
I've had this problem too.

**Comment by michaelpopi1** [comment]
> #40
> 
> read this thread

i have this issue as well, this didnt really help

**Comment by harbassan** [comment]
screenshot the logs, instructions: https://github.com/harbassan/spicetify-stats/issues/41#issuecomment-1814179793

**Comment by harbassan** [comment]
updated it, see if it fixes

**Comment by michaelpopi1** [comment]
> updated it, see if it fixes

sorry for the late reply
i just updated it and it still wasnt working but now it seems like it did after i enabled devtools to ss them for you for some reason? idk if that was just a coincidence or not

**Comment by harbassan** [comment]
it probably just needed to refresh the data after the update.
