### ISSUE TITLE
Failed To Fetch Library Stats

### ISSUE THREAD

**Issue by MrJIBH** [harbassan/spicetify-stats#41]
Library dont work, i htink that its my songs count (4.300)

![image](https://github.com/harbassan/spicetify-stats/assets/76195813/3530cf6e-1b50-49bb-9324-f8a92ede165f)

**Comment by harbassan** [comment]
can i see the logs please, run the command `spicetify enable-devtools` and then `ctrl-shift-I` on spotify window, go to the console tab and you should see some error relating to 'stats'. Send me a screenshot of that.

**Comment by billzhen870** [comment]
> can i see the logs please, run the command `spicetify enable-devtools` and then `ctrl-shift-I` on spotify window, go to the console tab and you should see some error relating to 'stats'. Send me a screenshot of that.


<img width="1389" alt="截屏2023-11-16 下午7 00 37" src="https://github.com/harbassan/spicetify-stats/assets/87466657/c4d2fae1-b5ce-41b8-aea9-c7f712aed27c">
here is my error log, on a mac

**Comment by harbassan** [comment]
fixed it, try re downloading the dist branch and it should work.
