### ISSUE TITLE
[Bug] app crashes when clicking library tab

### ISSUE THREAD

**Issue by jeroentvb** [harbassan/spicetify-stats#47]
Since 0.2.0 the app crashes for me when clicking the library tab.

This is my console at the time of crashing:
![image](https://github.com/harbassan/spicetify-stats/assets/36192730/3146f0cc-68cc-4dff-8709-73cec55c0245)

**Comment by jeroentvb** [comment]
Hmm, after about 5-10 times of crashing and reloading spotfiy it seems to be working again..

**Comment by harbassan** [comment]
yeah looks like this is just to do with the library data differences between the versions. After the first fetch it would work fine. I should probably handle this better in the future tho.
