### ISSUE TITLE
blank Artists and Genres pages

### ISSUE THREAD

**Issue by itmealice** [harbassan/spicetify-stats#50]
In my statistics tab, only the Tracks and Library pages load any information, while the Artists and Genres tabs remain completely blank. Both Spicetify and this app are up to date. I also can't see any stats errors in console, unless this is one.

![image](https://github.com/harbassan/spicetify-stats/assets/90822053/489978b5-7c89-43a0-aa25-d1eab453de28)

![Spotify_938RttGRpy](https://github.com/harbassan/spicetify-stats/assets/90822053/61118f1c-487e-4d86-8e44-aa670f4660f0)

![Spotify_eHdQ0lOzIK](https://github.com/harbassan/spicetify-stats/assets/90822053/b9e8d652-9574-48c5-a7e3-dab34b324fcc)

**Comment by harbassan** [comment]
There would be some other errors in there, they might not show up as red, but they will start with 'stats' and might contain a link.
