### ISSUE TITLE
[Feature Request] Add a time range dropdown to the Library tab.

### ISSUE THREAD

**Issue by mmaarij** [harbassan/spicetify-stats#51]
I think there should be a dropdown option to select a specific time range for the stats on the library page as well. So that we're able to view Total Minutes/Hours for a specific time period just like we're able to do in the Genres Page (past month, past year, all time etc).

**Comment by harbassan** [comment]
How would this work though? Basically the library page is just the overall stats of all the songs in your playlists, so I don't get how there could be time ranges on it. Could you explain what you mean a bit more?

**Comment by mmaarij** [comment]
> How would this work though? Basically the library page is just the overall stats of all the songs in your playlists, so I don't get how there could be time ranges on it. Could you explain what you mean a bit more?

Yes I get that they're the stats of all the songs in my playlists / all playlists. But, what I wanted was that there could be a time range option that measures these stats over just a specific period. This way users could, for example, get information on how many total minutes they've listened to their own playlists / all playlists over the past year.

I hope this makes the use case of my request more clearer.

**Comment by harbassan** [comment]
Ah, unfortunately this isn't possible to do without some sort of server to store listening information, and that is far too complicated for this project.
