### ISSUE TITLE
[Feature Request] Add the time spent listening to artists and times we listened to our top tracks

### ISSUE THREAD

**Issue by harsharora08** [harbassan/spicetify-stats#55]
It would be cool if we could see the time we have spent listening to our favorite artists and also consolidated time we listened to spotify in a certain period of time.
And the play count of our top tracks.

Thank you.
Love the app.

**Comment by harbassan** [comment]
This would be difficult to add to the app, and the best I could probably do would be counting plays/time listened only on the device that spicetify is on, because counting them all would require a server. I might add it anyway in the future, but not at the moment.
