### ISSUE TITLE
Items misaligning after the latest update

### ISSUE THREAD

**Issue by harsharora08** [harbassan/spicetify-stats#60]
After the latest spicetify update, `v2.31.0`, the navbar on the top of stats page is getting misaligned.

![image](https://github.com/harbassan/spicetify-apps/assets/41362690/475d1f21-3eaf-489e-a756-73f3cd464b7f)

Preview is attached

_Kindly let me know if this is happening only in my client or if it is universal_

**Comment by harbassan** [comment]
It seems like its probably a theme related issue
