### ISSUE TITLE
does not have index.js

### ISSUE THREAD

**Issue by ServalFake** [harbassan/spicetify-stats#7]
Hi, I love the idea, but after I followed the install instructions it came up with an error: "file does not have index.js"

**Comment by ServalFake** [comment]
Versions 
Spotify: 1.2.10.760.g52970952
Spicetify v2,18.1

**Comment by harbassan** [comment]
can you check inside the folder wether the index.js file is in there. Make sure you've downloaded the dist branch and put it into the right place.

**Comment by ServalFake** [comment]
it does have the index, but for whatever reason I'm still receiving the error. I'm not sure if this is what's supposed to happen but when I open the index file this is the message I receive
![Screenshot 2023-05-11 050053](https://github.com/harbassan/spicetify-stats/assets/133217496/047dcfc2-b054-4e56-bf5c-c9f5e157b171)

**Comment by ServalFake** [comment]
oh, and dont pay mind to the name, I already changed the name to stats, I was just trying a couple different things to resolve the error

**Comment by harbassan** [comment]
oh right the issue is just that you have the folder within a folder, whereas it should just be the folder with the files in the customapps folder.

**Comment by ServalFake** [comment]
Ohhh, it worked! Thanks so much for the help!
