### ISSUE TITLE
"Tracks" section doesn't work

### ISSUE THREAD

**Issue by indexcss** [harbassan/spicetify-stats#8]
![image](https://github.com/harbassan/spicetify-stats/assets/133282246/da196e2b-80c7-4e60-a647-17326a21fffd)
when I go to the tracks section I get a error saying Something went wrong
Everything thing else works

**Comment by harbassan** [comment]
can you show me the console as the error occurs.

**Comment by indexcss** [comment]
It shows this 
![image](https://github.com/harbassan/spicetify-stats/assets/133282246/84bc1b51-ac6e-403f-9a7a-1e9ad8b6c90d)
I got it to work for a little bit and now its doing this again

**Comment by harbassan** [comment]
oh yeah I understand why there's an error, ill fix it soon and then let you know

**Comment by harbassan** [comment]
@indexcss  install the latest release and that should hopefully fix the issue
